{{- $appname := printf "%s" (include "name" .) -}}
{{- if .Values.configfiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" $appname }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $appname }}
    appver: "{{ $.Values.image.tag }}"
    chart: "{{$.Chart.Name}}-{{$.Chart.Version}}"
    release: "{{ $.Release.Name }}"
    helm.sh/chart: "{{$.Chart.Name}}-{{$.Chart.Version}}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-5"
data:
{{- range $key, $value := .Values.configfiles.data }}
  {{ $key }}: {{ tpl $value $ | quote }}
{{- end }}
{{- end }}

{{- if .Values.extensions }}
---
{{- range .Values.extensions}}
{{- if .configfiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s-config" $appname .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $appname }}
    appver: "{{ $.Values.image.tag }}"
    chart: "{{$.Chart.Name}}-{{$.Chart.Version}}"
    release: "{{ $.Release.Name }}"
    helm.sh/chart: "{{$.Chart.Name}}-{{$.Chart.Version}}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-5"
data:
{{- range $key, $value := .configfiles.data }}
  {{ $key }}: {{ tpl $value $ | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
